apiVersion: apps/v1
kind: Deployment
metadata:
  name: stabledeployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: stable-container
        image: fforfrodo/helloworld:latest
        ports:
        - containerPort: 80