apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaleddeployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: hello-world-container
          image: fforfrodo/helloworld:latest
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"